# Generated by Django 5.0.6 on 2024-05-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='liked_colleges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.colleges'),
        ),
    ]
