# Generated by Django 5.0.6 on 2024-05-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_alter_colleges_liked_by'),
        ('users', '0002_myusers_liked_colleges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='liked_colleges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.colleges'),
        ),
    ]
