# Generated by Django 5.0.6 on 2024-05-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_markedcolleges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='liked_colleges',
        ),
    ]
