# Generated by Django 5.0.6 on 2024-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_rename_imgage_category_image'),
        ('users', '0005_remove_myusers_liked_colleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedcolleges',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='markedcolleges',
            unique_together={('student', 'marked_college')},
        ),
    ]
