# Generated by Django 5.0.6 on 2024-06-16 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0014_remove_colleges_parent_subcategory_and_more'),
        ('users', '0008_delete_markedcolleges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='marked_colleges',
        ),
        migrations.CreateModel(
            name='MarkedColleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('marked_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.colleges')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'marked_college')},
            },
        ),
    ]
