# Generated by Django 5.0.6 on 2024-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_myusers_marked_colleges_markedcolleges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='myusers',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
