# Generated by Django 5.0.6 on 2024-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_remove_colleges_liked_by_colleges_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='colleges',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colleges',
            name='hostel_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colleges',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colleges',
            name='library_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colleges',
            name='other_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colleges',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
