# Generated by Django 5.0.6 on 2024-05-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_rename_image_colleges_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleges',
            name='liked_by',
        ),
    ]
