# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_remove_colleges_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
