# Generated by Django 5.0.6 on 2024-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_colleges_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('imgage', models.ImageField(blank=True, null=True, upload_to='')),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='category',
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='subcategory',
        ),
    ]
