# Generated by Django 5.0.6 on 2024-05-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_category_subcategory_remove_colleges_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.subcategory'),
        ),
        migrations.AddField(
            model_name='colleges',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.category'),
        ),
    ]
