# Generated by Django 5.0.6 on 2024-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_colleges_subcategory_colleges_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='courses',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
