# Generated by Django 5.0.6 on 2024-05-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_subcategory_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imgage',
            new_name='image',
        ),
    ]
