# Generated by Django 5.0.6 on 2024-06-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_rename_imgage_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='Subcategory',
            new_name='parent_subcategory',
        ),
    ]
