# Generated by Django 5.0.6 on 2024-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_rename_subcategory_colleges_parent_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleges',
            name='parent_subcategory',
        ),
        migrations.AddField(
            model_name='colleges',
            name='parent_subcategories',
            field=models.ManyToManyField(blank=True, to='colleges.subcategory'),
        ),
    ]
