# Generated by Django 5.0.6 on 2024-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0014_remove_colleges_parent_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
